#!/usr/bin/env python3

# This file will be used to help match song strings. It is a list of lists.
# Each inner list is one song
# The first name in the inner list we will use as the 'real' name.
# Songs must match one of the entries after cleaning, exactly or with a high scoring fuzzy text match

# List is currently very dirty and used to extract rules for cleaning

SONGS = 
    [
        ["A Little Light"],
        ["Althea", "Althea (1) $", "Althea (Tape Flip After Song)"],
        ["And We Bid You Goodnight"],
        ["Big River", "Big River (1)"],
        ["Bird Song","Bird Song, Set Break", "Birdsong"],
        ["Black Muddy River"],
        ["Black Peter"],
        ["Black Throated Wind"],
        ["Blow Away"],
        ["Cassidy"],
        ["China Cat Sunflower", "Chinacat Sunflower"],
        ["Cold Rain & Snow", "Cold Rain And Snow", "Cold Rain And Snow (Start Cuts In)", "Cold Rain and Snow", "Cold Rain and Snow %", "Cold, Rain & Snow"],
        ["Crazy Fingers"],
        ["Crowd/Tuning", "Crowd/tuning", "Crowd/tunng", "Tuning", "Tuning", "We Want Phil'", "crowd", "crowd - tuning", "crowd sings Happy Bday", "crowd/tuning", "tuning", "tuning/crowd", "we want phil"],
        ["Deal", "Deal, Set Break"],
        ["Dear Mr Fantasy", "Dear Mr. Fantasy"],
        ["Don't Ease", "Don't Ease Me In", "Don't Ease Me In, Set Break", "Don't Ease me In"],
        ["Drum..s > (Tape Flip Near End)", "Drums", "Drums & Mardi Gras Parade*", "Drums continued", "Drums//", "Drums>Space", "Drumz", "drums"],
        ["E: It's All Over Now, Baby Blue"],
        ["E: Knockin' On Heaven's Door"],
        ["E: We Bid You Goodnight"],
        ["Easy To Love You", "Easy to Love You", "Easy to Love You +"],
        ["Encore Break", "Encore Break (Added From Set 1 Tape)", "Encore..Break (Tape Pause Between)"],
        ["Estimated Prophet"],
        ["Eyes Of The World", "Eyes of the World"],
        ["Feel Like A Stranger", "Feel Like a Stranger", "Feel Like a Stranger %"],
        ["Fire On The Mountain", "Fire on the Mountain"],
        ["Gimme Some Lovin'", "Gimmie Som eLovin'", "Gimmie Some Lovin'"],
        ["Good Time Blues", "Good Times Blues"],
        ["Greatest Story", "Greatest Story Ever Told", "Greatest Stroy Ever Told"],
        ["Happy Birthday to Phil"],
        ["Hell In A Bucket", "Hell in a Bucket"],
        ["I Know You Rider", "I Know you Rider"],
        ["I Need A Miracle","I Need a Miracle"],
        ["I Will Take You Home", "I will take you Home"],
        ["Iko Iko", "Iko Iko ->"],
        ["It's All Over Now Baby Blue", "It's All Over Now, Baby Blue"],
        ["Jack A Roe"],
        ["Jack Straw", "Jack Straw (if you listen, you can hear Brett laugh)"],
        ["Jack-A-Roe", "Jack-a-Roe"],
        ["Jam"],
        ["Just A Little Light"],
        ["Just Like Tom Thumb Blues", "Just Like Tom Thumb's Blues"],
        ["Just a Little Light"],
        ["Knockin' On Heaven's Door", "Knockin' on Heaven's Door"],
        ["Let It Grow", "Let It Grow, set Break"],
        ["Let The Good Times Roll", "Let the Good Times Roll"],
        ["Let it Grow"],
        ["Little Red Rooster"],
        ["Loose Lucy", "Loose Lucy (Direct Tape Flip After Song)"],
        ["Loser"],
        ["Mama Tried"],
        ["Man Smart (Woman Smarter)", "Man Smart (Women Smarter)", "Man Smart (Women are Smarter)", "Man Smart, Woman Smarter", "Women Are Smarter"],
        ["Memphis Blues", "Memphis Blues (First Few Notes Missing)", "Memphis Blues Again"],
        ["Mississippi Half Step", "Mississippi Half Step Uptown Toodeloo", "Mississippi Half-Step", "Mississippi Half-Step Uptown Toodleloo", "Mississippi Half-Step..(Ending Missing/Tape Flip)"],
        ["Mock Turtle Jam > (2)"],
        ["Morning Dew"],
        ["Never Trust A Woman", "Never Trust a Woman"],
        ["New Minglewood Blues"],
        ["Not Fade Away", "Not Fade Away %"],
        ["Peggy O", "Peggy-O"],
        ["Playin' In The Band", "Playin' in the Band", "Playing In The Band", "Playing In the Band", "Playing in the Band"],
        ["Playin' Jam", "Playing Jam"],
        ["Playin' Reprise"],
        ["Queen Jane Approximately", "Queen Jane Approximately (Tape Flip Directly After Song)", "queen jane approximately"],
        ["Ramble On Rose", "Ramble on Rose"],
        ["Revolution", "Revolution #"],
        ["Row Jimmy"],
        ["Sampson & Delilah", "Samson", "Samson & Delilah", "Samson And Delilah", "Samson and Delilah"],
        ["Scarlet Begonias"],
        ["Ship Of Fools", "Ship of Fools"],
        ["Spa//ce", "S..pace (Tape Flip At Start)", "Spac..e > (Tape Flip)", "Space", "Space > (2)", "space"],
        ["Spoonful"],
        ["Stagger Lee"],
        ["Standing On The Moon", "Standing on the Moon"],
        ["Stella Blue"],
        ["Stuck Inside Of Mobile With The Memphis Blues Again", "Stuck Inside of Mobile With The Memphis Blue Again", "Stuck Inside of Mobile with the Memphis Blues Again"],
        ["Sugar Magnolia"],
        ["Sugaree"],
        ["Take You Home"],
        ["Tennessee Jed"],
        ["Terra//pin", "Terrapin", "Terrapin Station", "Terrapin Station > Jam"],
        ["The Last Time", "The Last Time (First Few Notes Missing)", "This Could Be The Last Time"],
        ["The Music Never Stopped"],
        ["The Other One"],
        ["The Wheel"],
        ["Throwing Stone//s", "Throwing Stones", "Throwing Stones > (3)"],
        ["Tom Thumb Blues", "Tom Thumb's Blues", "Tom Thumbs Blues"],
        ["Touch Of Gray", "Touch Of Grey", "Touch of Grey"],
        ["Truckin'"],
        ["Turn On Your Love Light", "Turn On Your Lovelight", "Turn on Your Love Light", "Turn on Your Lovelight"],
        ["Uncle John's Band"],
        ["Victim Or The Crime", "Victim or the Crime"],
        ["Walkin' Blues", "Walking Blues"],
        ["We Bid You Good Night"],
        ["Wharf Rat", "Whart Rat"],
        ["When I Paint My Masterpiece", "When I Paint My Masterpiece (Start Cuts In)"],
        ["encore break"],
]