#!/usr/bin/env python3

# This file will be used to help match song strings. It is a list of lists.
# Each inner list is one song
# The first name in the inner list we will use as the 'real' name.
# Songs must match one of the entries after cleaning, exactly or with a high scoring fuzzy text match

# List is currently very dirty and used to extract rules for cleaning

SONGS = [["Ain't Superstitious"],
         ["A Little Light"],
         ["Ain’t Gonna’ Work On Maggie’s Farm No More", "Maggies Farm"],
         ["Alabama Getaway"],
         ["Alhambra"],
         ["Alligator"],
         ["All Too Much"],
         ["Althea"],
         ["All Along The Watchtower"],
         ["And We Bid You Goodnight"],
         ["Are You Lonely For Me Baby?"],
         ["Attics Of My Life", "Attics"],
         ["Around & Around", "Around and Around", "A & A", "A&A"],
         ["Baba O'Riley"],
         ["Baby What You Want Me To Do", "Baby What You Want Me To Do?"],
         ["Bad Moon Rising"],
         ["Ballad Of A Thin Man"],
         ["Bass & Drums", "Bill & Phil"],
         ["Bass Solo", "Phil Zone"],
         ["Banana Boat Song"],
         ["Barbara Allen"],
         ["Beat It On Down The Line"],
         ["Beautiful Jam", "beautiful jam�"],
         ["Believe It Or Not"],
         ["Bertha", "bertha (serious sbd mix issues)"],
         ["Beat It On Down The Line", "BIODTL", "B.I.O.D.T.L"],
         ["Big Boss Man"],
         ["Big Railroad Blues", "Big RR Blues"],
         ["Bob & Brent jam", "Bob and Brent Jam"],
         ["Bo Diddley-itis (?)"],
         ["Built To Last"],
         ["Big River"],
         ["Big Boy Pete"],
         ["Bird Song", "Bird Song/Set Break With Carlos Santana", "Birdsong"],
         ["Blackbird"],
         ["Black Muddy River"],
         ["Black Peter"],
         ["Black Queen"],
         ["Black Throated Wind", "BT Wind"],
         ["Blow Away", "drops or cuts in Blow Away @4:27", "Blow Away -> wait-a-minute rap -> Blow Away"],
         ["Blues For Allah"],
         ["Bob Star"],
         ["Box Of Rain"],
         ["Bring Me My Shotgun"],
         ["Brother Esau", "My Brother Esau"],
         ["Brokedown Palace", "Brokedown..Palace ( End Missing, Patched ** )"],
         ["Broken Arrow"],
         ["Brown Eyed Women", "bew", "gd79-07-01 s1 t09 brown eyed womem"],
         ["Bye Bye Love"],
         ["California Earthquake"],
         ["Casey Jones", "KC Jones"],
         ["Cassidy"],
         ["Candyman"],
         ["Caution", "caution (do not stop on the tracks)"],
         ["CC Rider", "C.C. Rider", "C. C. Rider", "C.C. Rider"],
         ["Chanting by Guyto Monks", "Guyto Monks"],
         ["Chimes Of Freedom"],
         ["China Cat Sunflower"],
         ["Childhood's End"],
         ["Children Of The Eighties"],
         ["China Doll"],
         ["Cold Jordan"],
         ["Cold Rain & Snow", "Cold Rain And Snow"],
         ["Comes A Time"],
         ["Corrina"],
         ["Cosmic Charlie"],
         ["Crazy Fingers"],
         ["Cryptical Envelopment"],
         ["Cumberland Blues"],
         ["Dancin' In The Streets", "Dancin' In the Street", "Dancing In The Streets"],
         ["Dark Star"],
         ["Dark Star Jam"],
         ["Dark Hollow"],
         ["Days Between", "The Days Between"],
         ["Day-O"],
         ["Day Job", "Keep Your Day Job"],
         ["Day Tripper"],
         ["Deal"],
         ["Death Don't Have No Mercy"],
         ["Deep Elem Blues"],
         ["Devil In A Blue Dress"],
         ["Desolation Row"],
         ["Dear Mr. Fantasy", "Dear Mister Fantasy"],
         ["Dire Wolf", "Dire Wolf.. (Ending Notes Cut)"],
         ["Do Right Woman, Do Right Man", "Do Right Woman"],
         ["Don't Ease", "Don't Ease Me In"],
         ["Don't Need Love", "I Don't Need Love"],
         ["Don't Think Twice, It's Alright", "Don't Think Twice"],
         ["Down In The Bottom"],
         ["Do You Wanna Dance?", "Do You Wanna Dance"],
         ["Drink Up And Go Home"],
         ["Drums", "Drums & Mardi Gras Parade*", "Drums continued", "Drums//", "Drumz", "drums", "drums > (tape flip near end)", "Drums.. > ( First Minute Only, Rest MIA on Tape )", "Electronic Percussion", "drums (with Billy Cobham)", "drum break", "rhythm devils", "rhythm section jam", "beginning of drums?"],
         ["Dupree's Diamond Blues"],
         ["Easy Answers"],
         ["Easy To Love You"],
         ["Easy Wind"],
         ["Eighteen Children"],
         ["El Paso"],
         ["Empty Pages"],
         ["Equinox"],
         ["Estimated Prophet"],
         ["Eternity"],
         ["Every Time You Go Away"],
         ["Eyes Of The World", "Eyes-> Jam->", "eyes of [tape flip/crossfade patch] the world"],
         ["Far From Me"],
         ["Fever"],
         ["Foolish Heart"],
         ["Forever Young"],
         ["Friend Of The Devil", "FOTD"],
         ["From The Heart Of Me"],
         ["Frozen Logger", "The Frozen Logger"],
         ["Feedback"],
         ["Feel Like A Stranger", "Stranger"],
         ["Fire On The Mountain", "Fire"],
         ["Flibberty Jib", "Flibberty Jib On The Bippity Bop"],
         ["Franklin's Tower", "Franklins Tower"],
         ["Frankie Lee and Judas Priest", "Frankie Lee and Judas Preist"],
         ["Gentleman Start Your Engines"],
         ["Going Down The Road Feeling Bad", "GDTRFB", "G.D.T.R.F.B.", "g.d.t.r.f.b", "going down the road"],
         ["Gimme Some Lovin'"],
         ["Good Time Blues"],
         ["Gloria"],
         ["Good Golly Miss Molly"],
         ["Good Lovin'", "Good Loving"],
         ["Good Morning Little Schoolgirl"],
         ["Good Vibrations"],
         ["Got My Mojo Workin'"],
         ["Gotta Serve Somebody", "Serve Somebody"],
         ["Greatest Story", "Greatest Story Ever Told"],
         ["Green Green Grass Of Home"],
         ["Hamza Jam", "dead join hamza", "hamza jam #2"],
         ["Handsome Cabin Boy"],
         ["Hand Jive", "Willie & The Hand Jive"],
         ["Happiness Is Drumming"],
         ["Happy Birthday"],
         ["Hard To Handle"],
         ["Heaven Help The Fool"],
         ["He's Gone"],
         ["Hell In A Bucket", "Bucket", "hell ina bucket"],
         ["Help Me Rhonda"],
         ["Help On The Way"],
         ["Here Comes Sunshine"],
         ["Hey Bo Diddley"],
         ["Hey Jude", "Hey Jude Finale"],
         ["Hey Pocky Way"],
         ["Hi-Heeled Sneakers"],
         ["Highway 61"],
         ["High Time", "High Time (Tape Flip Directly After, Very End Cut)"],
         ["Hoochie Coochie Man"],
         ["Hully Gully"],
         ["(I Can't Get No) Satisfaction", "(Encore) Satisfaction", "Satisfaction"],
         ["If I Had The World To Give"],
         ["If The Shoe Fits", "Show Fits"],
         ["I Get Around"],
         ["I Just Want To Make Love To You"],
         ["I'm A Man"],
         ["It's All Over Now", "Used To Love Her"],
         ["It's All Over Now, Baby Blue", "baby blue"],
         ["It Takes A Lot To Laugh, It Takes A Train To cry", "Train To Cry"],
         ["It Must Have Been The Roses", "imhbtr"],
         ["I Fought The Law"],
         ["I Hear A Voice Callin'"],
         ["I Know You Rider"],
         ["I Need A Miracle"],
         ["I’ve Got a Mind to Give Up Living", "A Mind to Give Up Livin'"],
         ["I Want To Tell You"],
         ["I Washed My Hands In Muddy Water"],
         ["I Will Take You Home"],
         ["Iko Iko", "Aiko Aiko", "Aiko-Aiko", "Iko-Iko", "aiko- aiko"],
         ["Intro"],
         ["I'm A King Bee", "King Bee"],
         ["I'm A Hog For You Baby", "hog for you baby"],
         ["It's A Man's World", "It's A Man's, Man's World"],
         ["It Hurts Me Too", "Hurts Me Too"],
         ["I've Been All Around this World"],
         ["Jam", "JAM!", "Jam (2)", "JAM (Bob, Bruce, Jerry)", "two soldiers jam", "bruce and drummers jam", "piano jam", '/jam -", "brent jam", "ja.m -', "Mock Turtle Jam"],
         ["Jack Straw", "jack straw (if you listen, you can hear brett laugh)", "Jack Straw * ( Cuts In, Start Patched ** )"],
         ["Jack-A-Roe", "Jack A Roe"],
         ["Joey"],
         ["Johnny B. Goode", "J.B. Goode", "JB Goode", "johnnie b goode"],
         ["Just A Little Light"],
         ["Just Like Tom Thumb's Blues"],
         ["Katie Mae"],
         ["KC Moan"],
         ["Keep On Growing"],
         ["Knockin' On Heaven's Door"],
         ["Lady Di and I", "Lady Di"],
         ["Lazy Lightning"],
         ["Lazy River Road"],
         ["Let It Grow"],
         ["Let Me Sing Your Blues Away", "let / me sing your blues away", "LMSYBA"],
         ["Let The Good Times Roll", "LTGTR"],
         ["Let it Grow"],
         ["Liberty"],
         ["Little Red Rooster"],
         ["Little Bunny Foo-Foo", "Little Bunny Foo Foo"],
         ["Looks Like Rain", "LL Rain", "L.L. Rain"],
         ["Long Black Limousine"],
         ["Loose Lucy"],
         ["Love The One You're With"],
         ["Lost Sailor"],
         ["Lucifer's Eyes"],
         ["Lucy In The Sky With Diamonds", "LSD", "L.S.D."],
         ["Loser"],
         ["Maggie's Farm"],
         ["Masons Children", "masons children"],
         ["Maybe You Know", "Maybe You Know How I Feel"],
         ["Mama Tried"],
         ["Man Smart (Woman Smarter)", "Man Smart (Women Smarter)", "Man Smart (Women are Smarter)", "Man Smart, Woman Smarter", "Women Are Smarter"],
         ["Mathilda", "Matilda Matilda", "Matilda"],
         ["Me & My Uncle", "Me And My Uncle"],
         ["Me & Bobby McGee", "Me and Bobby McGee"],
         ["Meet Me At The Bottom"],
         ["Memphis Blues Again", "Memphis Blues (First Few Notes Missing)"],
         ["Mexicali Blues"],
         ["Mexican Hat Dance"],
         ["Midnight Hour"],
         ["Might As Well"],
         ["Mind Left Body Jam", "Mind Left Body", "mud love buddy jam"],
         ["Minglewood Blues", "All New Minglewood Blues"],
         ["Mississippi Half Step", "Mississippi Half Step Uptown Toodeloo", "Mississippi Half-Step", "Mississippi Half-Step Uptown Toodleloo", "Half-Step", "Half Step", "just exactly perfect tuning>mississippi 1/2 step"],
         ["My Babe"],
         ["Mystery Train"],
         ["Mona"],
         ["Money Money"],
         ["Monkey and the Engineer"],
         ["The Mighty Quinn", "Mighty Quinn", "Quinn The Eskimo", "The Mighty Quinn (Quinn The Eskimo)"],
         ["Morning Dew"],
         ["Mr. Charlie"],
         ["Mr Tambourine Man"],
         ["Neighborhood Girls"],
         ["Never Trust A Woman"],
         ["Next Time You See Me"],
         ["New Minglewood Blues", "minglewood"],
         ["New Orleans"],
         ["New Speedway Boogie"],
         ["Nobody's Fault Jam", "Nobody's Fault But Mine Jam"],
         ["Not Fade Away", "NFA", "Not Fade..Away> (Tape Flip During,Remaining Added To First Tape)"],
         ["Not Fade Away Chant", "NFS Chant"],
         ["Okie From Muskogee"],
         ["Oh Babe It Ain't No Lie"],
         ["Oh Boy"],
         ["Ollin Agrageed"],
         ["One More Saturday Night", "Saturday Night"],
         ["On The Road Again"],
         ["Operator"],
         ["Passenger"],
         ["Peggy-O", "Peggy O", "Fennario", "peggio"],
         ["Picasso Moon"],
         ["Pigpen Rap"],
         ["Phil's Earthquake Space"],
         ["Playin' In The Band", "Playin' in the Band", "Playing In The Band", "Playing In the Band", "Playing in the Band", "Playin In The Band", "PITB", "Playin'"],
         ["Playin' Jam", "Playing Jam", "Jam out of Playin"],
         ["Playin' Reprise"],
         ["Pride Of Cucamonga"],
         ["Promised Land", "Promised..Land, set Break ( Power Loss Inside, Music Starts Back Up )", "the promised land - april fools!"],
         ["Proud Mary"],
         ["Queen Jane Approximately", "Queen Jane"],
         ["Ramble On Rose", "ROR"],
         ["Rain"],
         ["Rainy Day Women #12 and 35"],
         ["Reuben & Cherise"],
         ["Revolution"],
         ["Riot In Cell Block #9"],
         ["Ripple"],
         ["Rollin' and Tumblin'"],
         ["Road Runner", "(I'm A) Road Runner"],
         ["Rockin' Pneumonia"],
         ["Rosalie McFall"],
         ["Running Show Blues"],
         ["Run Rudolph Run"],
         ["Row Jimmy", "Row Jimmy (End Missing From Source Tapes *)", "row jimmy row"],
         ["Saint Of Circumstance"],
         ["Samba In The Rain"],
         ["Searchin'"],
         ["Set Break", "Set Break, Mickey Hart/Radio"],
         ["Sage & Spirit", "Sage and Spirit"],
         ["Salt Lake City"],
         ["Sampson & Delilah", "Samson"],
         ["Seastones", "seastones (from shnid=105755)", "phil & ned (seastones)"],
         ["Second That Emotion", "i second that emotion"],
         ["Scarlet Begonias"],
         ["Shakedown Street"],
         ["She Belongs To Me"],
         ["Shelter From The Storm"],
         ["Ship Of Fools"],
         ["Silver Threads & Golden Needles"],
         ["Sidewalks Of New York"],
         ["Sing Me Back Home"],
         ["Simple Twist Of Fate"],
         ["Slipknot", "Slipknot!"],
         ["Space", "Spa//ce", "S..pace (Tape Flip At Start)", "Spac..e > (Tape Flip)", "Space > (2)", "space", "Space.. (tape flip after space,some of space missing)", "Space (with locotomotive airhorn) >", "silent way jam > space", "spa/ce", "egyptian space"],
         ["Spanish Jam"],
         ["Spoonful"],
         ["Slow Blues (unknown title)"],
         ["Slow Train Coming"],
         ["Smokestack Lightning"],
         ["Smokestack/Spoonful jam"],
         ["So Many Roads"],
         ["Stagger Lee"],
         ["Stars & Stripes Forever"],
         ["St. Stephen"],
         ["Standing On The Moon", "Standing on the Moon", "sotm", "SOTM"],
         ["Stella Blue", "stella [tape flip/crossfade patch] blue"],
         ["Stir It Up"],
         ["Stir It Up Jam"],
         ["Stronger Than Dirt"],
         ["Stuck Inside Of Mobile With The Memphis Blues Again", "Stuck Inside Of Mobile"],
         ["Supplication"],
         ["Sugar Magnolia"],
         ["Sunrise"],
         ["Sunshine Daydream", "SSDD"],
         ["Sugaree"],
         ["Take It All Off"],
         ["Take You Home"],
         ["Take Me To The River"],
         ["That Would be Something"],
         ["The Main Ten"],
         ["Tell Mama", "Tell Moma"],
         ["Tennessee Jed", "t jed"],
         ["Terrapin", "Terrapin Station", "Terrapin Station > Jam"],
         ["Terrapin Reprise"],
         ["That's Alright Mama"],
         ["The Island"],
         ["The Last Time", "This Could Be The Last Time"],
         ["The Music Never Stopped"],
         ["The Race Is On"],
         ["The Other One", "Other One", "TOO"],
         ["The Same Thing"],
         ["The Stranger (Two Souls In Communion)"],
         ["The Times They Are A Changin'"],
         ["The Wheel", "Wheel"],
         ["The Weight", "Crowd - The Weight - Crowd outro"],
         ["They Love Each Other", "TLEO"],
         ["Throwing Stones", "Throwing Stones > {flip} {right channel problems} patched with gastwirt"],
         ["Tico Tico"],
         ["To Lay Me Down"],
         ["Tomorrow Is A Long Time"],
         ["Tomorrow Never Knows"],
         ["Tom Thumb Blues", "Tom Thumb's Blues", "Tom Thumbs Blues"],
         ["Tons Of Steel"],
         ["Touch Of Gray", "Touch Of Grey", "touch"],
         ["Truckin'", "Truckin"],
         ["Turn On Your Love Light", "Turn On Your Lovelight", "Lovelight"],
         ["Uncle John's Band", "ujb"],
         ["Uncle John's Band Reprise", "Uncle John's Reprise", "UJB reprise"],
         ["U.S. Blues", "US Blues", "US Blues (partial AUD patch)"],
         ["Unbroken Chain"],
         ["Valley Road"],
         ["Victim Or The Crime", "Victim"],
         ["Viola Lee Blues"],
         ["Visions Of Johanna"],
         ["Wake Up Little Susie"],
         ["Warriors Of The Sun"],
         ["Wave to the Wind"],
         ["Walkin' Blues", "Walking Blues"],
         ["Wang Dang Doodle"],
         ["Watching The River Flow"],
         ["Wave That Flag", "blue suede shoes", "blue suade shoes"],
         ["Whatcha Gonna Do"],
         ["Way To Go Home"],
         ["Weather Report Suite Prelude", "WRS Prelude"],
         ["Weather Report Suite", "WRS"],
         ["We Bid You Good Night"],
         ["We Can Run But We Can't Hide", "We Can Run"],
         ["Werewolves Of London"],
         ["West L.A. Fadeaway", "West LA Fadeaway", "West LA Fadeawy", "west l.a."],
         ["When Push Comes To Shove"],
         ["Where Have All The Heroes Gone"],
         ["Wharf Rat"],
         ["When I Paint My Masterpiece", "Masterpiece"],
         ["Who Do You Love?"],
         ["Wicked Messenger"],
         ["Wow Wow Hey Hey"],
         ["You Know I Love You So (Wo Wow Hey Hey)"],
         ["You Lied & Cheated", "You Lied And Cheated"],
         ["Youngblood"],
         ["You Win Again"],

         # sometime combos come up. Place here and fix later,
         ["MS 1/2 Step>The Weight"],
         ["Crazy Fingers > Playing Jam > Drums > Space >"],
         ["Help On The Way -> Slipknot! -> Franklin's Tower"],
         ["Dark Star jam > Bob/Phil/Bruce jam >"],
         ["Jam* -> Drums ->"],
         ["Jam > Bruce instrumental >"],
         ["Space / Spanish Jam >"],
         ["Space > Flibberty Jib > The Island"],
         ["mama tried-> mexicali blues"],
         ["far from me ; candyman"],
         ["Drums > Space", "Drums>Space", "D>S", "Drums>Space...(some of space missing)"],
         ["dear mr fantasy > hey jude finale > dear mr fantasy"],
         ["dear mr fantasy > hey jude reprise"],
         ["day-o / do you wanna dance?"],
         ["ain't superstitious -> down in the bottom"],
         ["cryptical envelopement -> the other one -> cryptical envelopment"],
         ["bass and drum solo > bass solo > bass and drum solo"],
         ["wrs prelude> wrs part 1"],
         ["saint stephen>not fade away>drums>saint stephen"],
         ["caution (do not stop on the tracks) >> who do you love?"],

         # weird named jams
         ["Dear Prudence Jam"],

         # oh dear
         ["Cosmic Charlie Tease"],

         # is this a track?
         ["Phil & Keyboards Jam"],
         ["Take A Step Back", "Step Back", "crowd/tuning > take a step back"],
         ["Adams Family"],
         ["Hamza El-Din"],
         ["Ken Nordine's Flibberdy Jib"],
         ["Countdown to Midnight", "Countdown"],
         ["Ken Kesey Rap"],
         ["A Day At The Dentist"],

         # stuff to ignore
         ["Encore Break", "Encore", "Encore Break (Added From Set 1 Tape)", "Encore..Break (Tape Pause Between)", "encore break"],
         ["Filler", "Filler - Me and Bobby McGee"],
         ["Crowd/Tuning", "Tuning", "We Want Phil'", "Crowd", "./-", "Bill Graham Speech", "its a bullshit lie", "Tuning (taper narrative)", "we want phil - 'there's this rumor goin' round...'", "funiculi funicula", "the sun king/stage preparations/marines' hymn", "house music /stage preparations", "stage preparations"],
         ["Studio Outtakes", "that's it for the other one - studio 1967 or 1968"],
         ["Fillers", "aiko ; to lay me down (3/27/88)"],

         # NRPS Songs
         ["NRPS", "seasons of my heart"],
         ["NRPS", "saw mill"],
         ["NRPS", "cowboy song (w/david bromberg)"],
         ["NRPS", "if you hear me when i'm leaving"],
         ["NRPS", "i don't know you, i don?t know you"],
         ["NRPS", "fair chance to know"],
         ["NRPS", "last lonely eagle"],
         ["NRPS", "seasons of my heart"],
         ["NRPS", "honky-tonk woman"],
         ["NRPS", "henry"],
         ["NRPS", "garden of eden"],
         ["NRPS", "fair chance to know"],
         ["NRPS", "i hear a voice callingnext time you see me"],
         ["NRPS", "i hear a voice calling"],
         ["NRPS", "next time you see me"],
         ["NRPS", "louisiana lady"],
         ["NRPS", "i don't know you"],
         ["NRPS", "fair chance to know"],
         ["NRPS", "so sad (to watch good love go bad)"],
         ["NRPS", "a voice from on high"],
         ["NRPS", "together again"],
         ["NRPS", "long black veil"],
         ["NRPS", "cecilia"],
         ["NRPS", "i don�t know you", "i don't know you"],
         ["NRPS", "sitting sun"],
         ["NRPS", "the bottle let me down"],
         ["NRPS", "the pump man"],
         ["NRPS", "fun, fun, fun"],
         ["NRPS", "runnin' back to you"],
         ["NRPS", "julie"],
         ["NRPS", "sweet lovin' one"],
         ["NRPS", "wall song > fresh green grass jam > wall song"],
         ["NRPS", "bill graham introduction/brown-eyed handsome man"],

         # Weird songs - likely reject
         ["UNKNOWN", "Rejected: change is gonna come (danko vocals)"],
         ["UNKNOWN", "Rejected: if you’ve ever been mistreated (richard manuel vocals)"],
         ["UNKNOWN", "Rejected: la di da day (danko vocals)"],
         ["UNKNOWN", "Rejected: let me wrap you in my warm and tender love (danko, garcia vocals)"],
         ["UNKNOWN", "Rejected: sing me back home"],
         ["UNKNOWN", "Rejected: change is gonna come (danko vocals)"],
         ["UNKNOWN", "Rejected: if you’ve ever been mistreated (richard manuel vocals)"],
         ["UNKNOWN", "Rejected: la di da day (danko vocals)"],
         ["UNKNOWN", "Rejected: let me wrap you in my warm and tender love (danko, garcia vocals)"],
         ["UNKNOWN", "homeward through the haze"],

         # reject as unknown studio
         ["STUDIO UNKNOWN", "low down payement jam (crosby & lagin, may be others)"],
         ["STUDIO UNKNOWN", "low down payement jam (crosby & lagin, may be others)"],
         ["STUDIO UNKNOWN", "x) crazy fingers (instr.) (ends with long reverb"],
         ["STUDIO UNKNOWN", "j. garcia:"],
         ["STUDIO UNKNOWN", "x) jam (funky stylish?) (fadeout) (6.46)"],
         ["STUDIO UNKNOWN", "drum intro > help on the way (instr., one"],
         ["STUDIO UNKNOWN", "(x) slipknot (x) (overlap with ending of track 8 on disc 1 of 4 above) (0.17)"],
         ["STUDIO UNKNOWN", "staccato jam (x) (7.25)"],
         ["STUDIO UNKNOWN", "(x) j. garcia playing stronger than dirt riff > drummers > j. garcia playing short stronger than dirt riffs (1.03)"],
         ["STUDIO UNKNOWN", "j. garcia soloing"],
         ["STUDIO UNKNOWN", "tape rewind (0.08)"],
         ["STUDIO UNKNOWN", "(x)"],
         ["STUDIO UNKNOWN", "(x) blues for allah intro-like jam (3.03)"],
         ["STUDIO UNKNOWN", "(x) staccato jam (6.16)"],
         ["STUDIO UNKNOWN", "jg:"],
         ["STUDIO UNKNOWN", "(slight 60hz hum in l channel at start) help on the way > slipknot (6.11)"],
         ["STUDIO UNKNOWN", "(x) noodling > help on the way > slipknot (7.20)"],
         ["STUDIO UNKNOWN", "(x) slipknot-type jam (3.07)"],
         ["STUDIO UNKNOWN", "(x) lazy lightning (fadeout) (0.16)"],
         ["STUDIO UNKNOWN", "j. garcia:"],
         ["STUDIO UNKNOWN", "(x) tape rewind > j. garcia:"],
         ["STUDIO UNKNOWN", "(x) franklin's tower (v) > just guitars and talk (x) (4.48)"],
         ["STUDIO UNKNOWN", "(x) noodling > help on the way > slipknot (7.15)"],
         ["STUDIO UNKNOWN", "j. garcia:"],
         ["STUDIO UNKNOWN", "j. garcia:"],
         ["STUDIO UNKNOWN", "king solomon's marbles [1: stronger than dirt, 2: milkin' the turkey]"],
         ["STUDIO UNKNOWN", "music never stopped type jam drop out ~2:40"],
         ["STUDIO UNKNOWN", "some bits of lazy lightning and some tuning and banter"],
         ["STUDIO UNKNOWN", "more bits of lazy lightning and slipknot, banter, ect"],

         # something went wrong
         ["Don't Ease Me In", "donãâãâãâãât ease me in"],
         ["Whatcha Gonna Do", "whatcha gonna do?"],
         ["NRPS", "i donãâãâãâãât know you"],
         ["NRPS", "workinãâãâãâãâ man blues"],
         ["NRPS", "fair chance to know"],
         ["NRPS", "last lonely eagle"],
         ["Good Lovin'", "good lovinãâãâãâãâ"],
    ]


# all the listing above that we would like removed from a setlist
NOT_SONGS = ["Encore Break", "Filler", "Crowd/Tuning", "Studio Outtakes", "Fillers", "NRPS", "STUDIO UNKNOWN", "UNKNOWN"]

# songs that need replacing with one or more other songs
REPLACE_SONGS = {
    "MS 1/2 Step>The Weight":["Mississippi Half Step", "The Weight"],
    "Crazy Fingers > Playing Jam > Drums > Space >":["Crazy Fingers", "Playin' Jam", "Drums", "Space"],
    "Help On The Way -> Slipknot! -> Franklin's Tower":["Help On The Way", "Slipknot", "Franklin's Tower"],
    "Dark Star jam > Bob/Phil/Bruce jam >":["Dark Star Jam", "Jam"],
    "Jam* -> Drums ->":["Jam", "Drums"],
    "Jam > Bruce instrumental >":["Jam"],
    "Space / Spanish Jam >":["Space", "Spanish Jam"],
    "Space > Flibberty Jib > The Island":["Space", "Flibberty Jib", "The Island"],
    "mama tried-> mexicali blues":["Mama Tried", "Mexicali Blues"],
    "far from me ; candyman":["Far From Me", "Candyman"],
    "Drums > Space":["Drums", "Space"],
    "dear mr fantasy > hey jude finale > dear mr fantasy":["Dear Mr. Fantasy", "Hey Jude", "Dear Mr. Fantasy"],
    "dear mr fantasy > hey jude reprise":["Dear Mr. Fantasy", "Hey Jude"],
    "day-o / do you wanna dance?":["Day-O", "Do You Wanna Dance?"],
    "ain't superstitious -> down in the bottom":["Ain't Superstitious", "Down In The Bottom"],
    "cryptical envelopement -> the other one -> cryptical envelopment":["Cryptical Envelopment", "Other One", "Cryptical Envelopment"],
    "bass and drum solo > bass solo > bass and drum solo": ["Bass & Drums", "Bass Solo", "Bass & Drums"],
    "Rejected: wrs prelude> wrs part 1":["Weather Report Suite Prelude", "Weather Report Suite", "WRS"],
    "saint stephen>not fade away>drums>saint stephen":["St. Stephen", "Not Fade Away", "Drums", "St. Stephen"],
    "caution (do not stop on the tracks) >> who do you love?": ["Caution", "Who Do You Love?"]
}
