# Missing: Cream Puff War
# key -> my_name
# value -> their name

TRANSLATIONS = {"Hully Gully":"(Baby) Hully Gully",
				"(I Can't Get No) Satisfaction":"(I Can't Get No) Satisfaction",
				"Road Runner":"(I'm A) Road Runner",
				"26 Miles Tuning":"26 Miles Tuning",
				"Addams Family Tuning":"Addams Family Tuning",
				"Alabama Getaway":"Alabama Getaway",
				"All Along The Watchtower":"All Along The Watchtower",
				"Alligator":"Alligator",
				"Althea":"Althea",
				"All I Have To Do Is Dream":"All I Have To Do Is Dream",
				"And We Bid You Goodnight":"And We Bid You Good Night",
				"And We Bid You Good Night Jam":"And We Bid You Good Night Jam",
				"Are You Lonely For Me Baby?":"Are You Lonely For Me Baby?",
				"Around & Around":"Around And Around",
				"Attics Of My Life":"Attics Of My Life",
				"Baba O'Riley":"Baba O'riley",
				"Baby What You Want Me To Do":"Baby What You Want Me To Do",
				"Bad Moon Rising":"Bad Moon Rising",
				"Ballad Of A Thin Man":"Ballad Of A Thin Man",
				"Banana Boat Song":"Banana Boat Song (Day O)",
				"Banks Of The Ohio":"Banks Of The Ohio",
				"Barbara Allen":"Barbara Allen",
				"Beat It On Down The Line":"Beat It On Down The Line",
				"Believe It Or Not":"Believe It Or Not",
				"Bertha":"Bertha",
				"Big Boss Man":"Big Boss Man",
				"Big Boy Pete":"Big Boy Pete",
				"Big Railroad Blues":"Big Railroad Blues",
				"Big River":"Big River",
				"Bird Song":"Bird Song",
				"Black Muddy River":"Black Muddy River",
				"Black Peter":"Black Peter",
				"Black Queen":"Black Queen",
				"Black Throated Wind":"Black Throated Wind",
				"Blackbird":"Blackbird",
				"Blow Away":"Blow Away",
				"Blue Moon":"Blue Moon",
				"Blues For Allah":"Blues For Allah",
				"Born Cross Eyed":"Born Cross Eyed",
				"Born On The Bayou":"Born On The Bayou",
				"Box Of Rain":"Box Of Rain",
				"Brokedown Palace":"Brokedown Palace",
				"Broken Arrow":"Broken Arrow",
				"Brown Eyed Women":"Brown Eyed Women",
				"Built To Last":"Built To Last",
				"Bye Bye Love":"Bye Bye Love",
				"C.C. Rider":"C.C. Rider",
				"California Earthquake":"California Earthquake (Whole Lotta Shakin' Goin' On)",
				"Can't Come Down":"Can't Come Down",
				"Candyman":"Candyman",
				"Casey Jones":"Casey Jones",
				"Cassidy":"Cassidy",
				"Cathy's Clown":"Cathy's Clown",
				"Caution":"Caution (Do Not Stop On Tracks)",
				"Caution Jam":"Caution (Do Not Stop On Tracks) Jam",
				"Checkin' Up":"Checkin' Up",
				"Childhood's End":"Childhood's End",
				"Children Of The Eighties":"Children Of The Eighties",
				"Chimes Of Freedom":"Chimes Of Freedom",
				"China Cat Sunflower":"China Cat Sunflower",
				"China Cat Sunflower Jam":"China Cat Sunflower Jam",
				"China Doll":"China Doll",
				"Chinatown Shuffle":"Chinatown Shuffle",
				"Chinese Bones":"Chinese Bones",
				"Clementine":"Clementine",
				"Close Encounters Jam":"Close Encounters Jam",
				"Cold Jordan":"Cold Jordan",
				"Cold Rain & Snow":"Cold Rain And Snow",
				"Come Back Baby":"Come Back Baby",
				"Comes A Time":"Comes A Time",
				"Corrina":"Corrina",
				"Cosmic Charlie":"Cosmic Charlie",
				"Crazy Fingers":"Crazy Fingers",
				"Cryptical Envelopment":"Cryptical Envelopment",
				"Cumberland Blues":"Cumberland Blues",
				"Dancin' In The Streets":"Dancing In The Street",
				"Dark Hollow":"Dark Hollow",
				"Dark Star":"Dark Star",
				"Dark Star Jam":"Dark Star Jam",
				"Day Tripper":"Day Tripper",
				"Days Between":"Days Between",
				"Dead Man, Dead Man":"Dead Man, Dead Man",
				"Deal":"Deal",
				"Dear Mr. Fantasy":"Dear Mr. Fantasy",
				"Dear Prudence Jam":"Dear Prudence Jam",
				"Death Don't Have No Mercy":"Death Don't Have No Mercy",
				"Death Letter Blues":"Death Letter Blues",
				"Deep Elem Blues":"Deep Elem Blues",
				"Desolation Row":"Desolation Row",
				"Devil In A Blue Dress":"Devil With The Blue Dress On",
				"Dire Wolf":"Dire Wolf",
				"Doin' That Rag":"Doin' That Rag",
				"Don't Ease":"Don't Ease Me In",
				"Don't Need Love":"Don't Need Love",
				"Don't Think Twice, It's Alright":"Don't Think Twice, It's Alright",
				"Down In The Bottom":"Down In The Bottom",
				"Drummers' Chant":"Drummers' Chant",
				"Drums":"Drums",
				"Dupree's Diamond Blues":"Dupree's Diamond Blues",
				"Early Morning Rain":"Early Morning Rain",
				"Easy Answers":"Easy Answers",
				"Easy To Love You":"Easy To Love You",
				"Easy Wind":"Easy Wind",
				"El Paso":"El Paso",
				"Empty Pages":"Empty Pages",
				"Estimated Prophet":"Estimated Prophet",
				"Eternity":"Eternity",
				"Every Time You Go Away":"Every Time You Go Away",
				"Eyes Of The World":"Eyes Of The World",
				"Fair Chance To Know":"Fair Chance To Know",
				"Far From Me":"Far From Me",
				"Feedback":"Feedback",
				"Feel Like A Stranger":"Feel Like A Stranger",
				"Fever":"Fever",
				"Fire On The Mountain":"Fire On The Mountain",
				"Foolish Heart":"Foolish Heart",
				"Forever Young":"Forever Young",
				"Foxy Lady Jam":"Foxy Lady Jam",
				"Franklin's Tower":"Franklin's Tower",
				"Friend Of The Devil":"Friend Of The Devil",
				"From The Heart Of Me":"From The Heart Of Me",
				"Funiculi Funicula":"Funiculi Funicula",
				"Games People Play":"Games People Play",
				"Gathering Flowers For The Master's Bouquet":"Gathering Flowers For The Master's Bouquet",
				"Gentlemen Start Your Engines":"Gentlemen Start Your Engines",
				"Get Back":"Get Back",
				"Gimme Some Lovin'":"Gimme Some Lovin'",
				"Gloria":"Gloria",
				"Going Down The Road Feeling Bad":"Goin' Down The Road Feeling Bad",
				"Good Golly Miss Molly":"Good Golly Miss Molly",
				"Good Lovin'":"Good Lovin'",
				"Good Lovin' Jam":"Good Lovin' Jam",
				"Good Morning Little Schoolgirl":"Good Morning Little Schoolgirl",
				"Good Times":"Good Times",
				"Good Vibrations":"Good Vibrations",
				"Goodnight Irene":"Goodnight Irene",
				"Got My Mojo Workin'":"Got My Mojo Workin",
				"Gotta Serve Somebody":"Gotta Serve Somebody",
				"Greatest Story":"Greatest Story Ever Told",
				"Green Green Grass Of Home":"Green Green Grass Of Home",
				"Green River":"Green River",
				"Handsome Cabin Boy Jam":"Handsome Cabin Boy Jam",
				"Hard To Handle":"Hard To Handle",
				"He Was A Friend Of Mine":"He Was A Friend Of Mine",
				"He's Gone":"He's Gone",
				"Heads Up":"Heads Up",
				"Heart Of Mine":"Heart Of Mine",
				"Heaven Help The Fool":"Heaven Help The Fool",
				"Hell In A Bucket":"Hell In A Bucket",
				"Help Me Rhonda":"Help Me Ronda",
				"Help On The Way":"Help On The Way",
				"Here Comes Sunshine":"Here Comes Sunshine",
				"Hey Bo Diddley":"Hey Bo Diddley",
				"Hey Jude":"Hey Jude",
				"Hey Pocky Way":"Hey Pocky Way",
				"Hi-Heeled Sneakers":"Hi-Heeled Sneakers",
				"Hide Away":"Hide Away",
				"High Time":"High Time",
				"Highway 61":"Highway 61 Revisited",
				"How Long Blues":"How Long Blues",
				"How Sweet It Is":"How Sweet It Is (To Be Loved By You)",
				"Ain't Superstitous":"I Ain't Superstitous",
				"I Don't Know You":"I Don't Know You",
				"I Fought The Law":"I Fought The Law",
				"I Get Around":"I Get Around",
				"A Mind to Give Up Livin'":"I Got A Mind To Give Up Livin'",
				"I Hear A Voice Callin'":"I Hear A Voice Callin'",
				"I Just Want To Make Love To You":"I Just Want To Make Love To You",
				"I Know You Rider":"I Know You Rider",
				"I Need A Miracle":"I Need A Miracle",
				"Second That Emotion":"I Second That Emotion",
				"I Want To Tell You":"I Want To Tell You",
				"I Want You":"I Want You",
				"I Washed My Hands In Muddy Water":"I Washed My Hands In Muddy Water",
				"I Will Take You Home":"I Will Take You Home",
				"I'll Be Your Baby Tonight":"I'll Be Your Baby Tonight",
				"I'll Go Crazy":"I'll Go Crazy",
				"I'm A Hog For You Baby":"I'm A Hog For You Baby",
				"I'm A King Bee":"I'm A King Bee",
				"I'm A Man":"I'm A Man",
				"I've Been All Around This World":"I've Been All Around This World",
				"I've Just Seen A Face":"I've Just Seen A Face",
				"If I Had The World To Give":"If I Had The World To Give",
				"If The Shoe Fits":"If The Shoe Fits",
				"Iko Iko":"Iko Iko",
				"Midnight Hour":"In The Midnight Hour",
				"It Hurts Me Too":"It Hurts Me Too",
				"It Must Have Been The Roses":"It Must Have Been The Roses",
				"It Takes A Lot To Laugh, It Takes A Train To Cry":"It Takes A Lot To Laugh It Takes A Train To Cry",
				"It's A Man's World":"It's A Man's World",
				"It's A Sin":"It's A Sin",
				"It's All Over Now":"It's All Over Now",
				"It's All Over Now, Baby Blue":"It's All Over Now, Baby Blue",
				"All Too Much":"It's All Too Much",
				"Jack-A-Roe":"Jack A Roe",
				"Jack Straw":"Jack Straw",
				"Jam":"Jam",
				"Joey":"Joey",
				"John Brown":"John Brown",
				"John's Other":"John's Other",
				"Johnny B. Goode":"Johnny B. Goode",
				"Just A Little Light":"Just A Little Light",
				"Just Like Tom Thumb's Blues":"Just Like Tom Thumb's Blues",
				"KC Moan":"KC Moan",
				"Kansas City":"Kansas City",
				"Katie Mae":"Katie Mae",
				"Keep On Growing":"Keep On Growing",
				"Day Job":"Keep Your Day Job",
				"Knockin' On Heaven's Door":"Knockin' On Heaven's Door",
				"Alhambra":"L'alhambra",
				"La Bamba":"La Bamba",
				"Lady Di And I":"Lady Di And I",
				"*Last Lonely Eagle":"Last Lonely Eagle",
				"Lazy Lightning":"Lazy Lightnin'",
				"Lazy River Road":"Lazy River Road",
				"Let It Be Me":"Let It Be Me",
				"Let It Grow":"Let It Grow",
				"Let It Rock":"Let It Rock",
				"Let Me In":"Let Me In",
				"Let Me Sing Your Blues Away":"Let Me Sing Your Blues Away",
				"Let The Good Times Roll":"Let The Good Times Roll",
				"Liberty":"Liberty",
				"Little Red Rooster":"Little Red Rooster",
				"Little Sadie":"Little Sadie",
				"Long Black Limousine":"Long Black Limousine",
				"Looks Like Rain":"Looks Like Rain",
				"Loose Lucy":"Loose Lucy",
				"Loser":"Loser",
				"Lost Sailor":"Lost Sailor",
				"Louie Louie":"Louie Louie",
				"Love The One You're With":"Love The One You're With",
				"Lucifer's Eyes":"Lucifer's Eyes",
				"Lucy In The Sky With Diamonds":"Lucy In The Sky With Diamonds",
				"Maggie's Farm":"Maggie's Farm",
				"Mama Tried":"Mama Tried",
				"Man Of Peace":"Man Of Peace",
				"Man Smart (Woman Smarter)":"Man Smart (Woman Smarter)",
				"Masons Children":"Mason's Children",
				"Mathilda":"Matilda, Matilda",
				"Maybe You Know":"Maybe You Know",
				"Me & Bobby McGee":"Me And Bobby Mcgee",
				"Me & My Uncle":"Me And My Uncle",
				"Mexicali Blues":"Mexicali Blues",
				"Might As Well":"Might As Well",
				"Mind Left Body Jam":"Mind Left Body Jam",
				"Mindbender":"Mindbender",
				"Mission In The Rain":"Mission In The Rain",
				"Mississippi Half Step":"Mississippi Half Step Uptown Toodeloo",
				"Mona":"Mona",
				"Money Money":"Money Money",
				"Monkey And The Engineer":"Monkey And The Engineer",
				"Morning Dew":"Morning Dew",
				"Mountain Jam":"Mountain Jam",
				"Mountains Of The Moon":"Mountains Of The Moon",
				"Mr. Charlie":"Mr. Charlie",
				"Mr Tambourine Man":"Mr. Tambourine Man",
				"My Baby Left Me":"My Baby Left Me",
				"Brother Esau":"My Brother Esau",
				"Neighbourhood Girls":"Neighbourhood Girls",
				"Never Trust A Woman":"Never Trust A Woman",
				"New Minglewood Blues":"New Minglewood Blues",
				"New Orleans":"New Orleans",
				"New Potato Caboose":"New Potato Caboose",
				"New Speedway Boogie":"New Speedway Boogie",
				"Next Time You See Me":"Next Time You See Me",
				"Nobody's Fault But Mine":"Nobody's Fault But Mine",
				"Nobody's Fault Jam":"Nobody's Fault But Mine Jam",
				"Not Fade Away":"Not Fade Away",
				"Ode For Billie Dean":"Ode For Billie Dean",
				"Oh Babe It Ain't No Lie":"Oh Babe It Ain't No Lie",
				"Oh Boy":"Oh Boy",
				"Okie From Muskogee":"Okie From Muskogee",
				"Ol' Slewfoot":"Ol' Slewfoot",
				"Old, Old House":"Old, Old House",
				"Ollin Arrageed":"Ollin Arrageed",
				"On The Road Again":"On The Road Again",
				"See That My Grave Is Kept Clean":"One Kind Favor",
				"One More Saturday Night":"One More Saturday Night",
				"Only A Fool":"Only A Fool",
				"Operator":"Operator",
				"Parchman Farm":"Parchman Farm",
				"Passenger":"Passenger",
				"Peggy-O":"Peggy O",
				"Peggy Sue":"Peggy Sue",
				"Picasso Moon":"Picasso Moon",
				"Playin' In The Band":"Playing In The Band",
				"Prisoner Blues":"Prisoner Blues",
				"Proud Mary":"Proud Mary",
				"Queen Jane Approximately":"Queen Jane Approximately",
				"Railroading The Great Divide":"Railroading The Great Divide",
				"Rain":"Rain",
				"Rainy Day Women #12 & #35":"Rainy Day Women #12 & #35",
				"Ramble On Rose":"Ramble On Rose",
				"Reuben & Cherise":"Reuben And Cherise",
				"Revolution":"Revolution",
				"Revolutionary Hamstrung Blues":"Revolutionary Hamstrung Blues",
				"Riot In Cell Block #9":"Riot In Cell Block",
				"Ripple":"Ripple",
				"Rockin' Pneumonia":"Rockin' Pneumonia & The Boogie Woogie Flu",
				"Rollin' And Tumblin'":"Rollin' And Tumblin'",
				"Rosalie Mcfall":"Rosalie Mcfall",
				"Row Jimmy":"Row Jimmy",
				"Run Rudolph Run":"Run Rudolph Run",
				"Sage & Spirit":"Sage And Spirit",
				"Saint Of Circumstance":"Saint Of Circumstance",
				"St. Stephen":"Saint Stephen",
				"Salt Lake City":"Salt Lake City",
				"Samba In The Rain":"Samba In The Rain",
				"Samson & Delilah":"Samson And Delilah",
				"Sawmill":"Sawmill",
				"Scarlet Begonias":"Scarlet Begonias",
				"Searchin'":"Searchin'",
				"*Seasons of My Heart":"Seasons Of My Heart",
				"Seastones":"Seastones",
				"Shakedown Street":"Shakedown Street",
				"She Belongs To Me":"She Belongs To Me",
				"She's Mine":"She's Mine",
				"Shelter From The Storm":"Shelter From The Storm",
				"Ship Of Fools":"Ship Of Fools",
				"Sick And Tired":"Sick And Tired",
				"Sidewalks Of New York":"Sidewalks Of New York",
				"Silver Threads & Golden Needles":"Silver Threads And Golden Needle",
				"Simple Twist Of Fate":"Simple Twist Of Fate",
				"Sing Me Back Home":"Sing Me Back Home",
				"Sittin' On Top Of The World":"Sittin' On Top Of The World",
				"Slipknot":"Slipknot!",
				"Slow R and B Instrumental":"Slow R and B Instrumental",
				"Slow Train Coming":"Slow Train",
				"Smokestack Lightning":"Smokestack Lightnin'",
				"Smokestack Lightnin' Jam":"Smokestack Lightnin' Jam",
				"So Many Roads":"So Many Roads",
				"Space":"Space",
				"Spanish Jam":"Spanish Jam",
				"Spoonful":"Spoonful",
				"Stagger Lee":"Stagger Lee",
				"Stander On The Mountain":"Stander On The Mountain",
				"Standing On The Moon":"Standing On The Moon",
				"Star Spangled Banner":"Star Spangled Banner",
				"Stella Blue":"Stella Blue",
				"Stir It Up":"Stir It Up",
				"Stronger Than Dirt":"Stronger Than Dirt Or Milkin' The Turkey",
				"Stuck Inside A Mobile With The Memphis Blues Again":"Stuck Inside A Mobile With The Memphis Blues Again",
				"Sugar Magnolia":"Sugar Magnolia",
				"Sugar Shack":"Sugar Shack",
				"Sugaree":"Sugaree",
				"Sunrise":"Sunrise",
				"Sunshine Daydream":"Sunshine Daydream",
				"Supplication":"Supplication",
				"Supplication Jam":"Supplication Jam",
				"Swing Low, Sweet Chariot":"Swing Low, Sweet Chariot",
				"Take A Step Back":"Take A Step Back Tuning",
				"Take It All Off":"Take It All Off",
				"Take Me To The River":"Take Me To The River",
				"Tangled Up In Blue":"Tangled Up In Blue",
				"Tell Mama":"Tell Mama",
				"Tennessee Jed":"Tennessee Jed",
				"Terrapin Station":"Terrapin Station",
				"That Would Be Something":"That Would Be Something",
				"That'll Be The Day":"That'll Be The Day",
				"That's Alright Mama":"That's All Right, Mama",
				"The Ballad Of Casey Jones":"The Ballad Of Casey Jones",
				"Frankie Lee and Judas Priest":"The Ballad Of Frankie Lee And Judas Priest",
				"The Boxer":"The Boxer",
				"The Eleven":"The Eleven",
				"The Eleven Jam":"The Eleven Jam",
				"Frozen Logger":"The Frozen Logger",
				"The Last Time":"The Last Time",
				"The Main Ten":"The Main Ten Jam",
				"The Mighty Quinn":"The Mighty Quinn (Quinn The Eskimo)",
				"The Music Never Stopped":"The Music Never Stopped",
				"The Only Time Is Now":"The Only Time Is Now",
				"The Other One":"The Other One",
				"The Other One Jam":"The Other One Jam",
				"Promised Land":"The Promised Land",
				"The Race Is On":"The Race Is On",
				"The Rub":"The Rub",
				"The Same Thing":"The Same Thing",
				"The Seven":"The Seven",
				"The Story Of A Brick":"The Story Of A Brick",
				"The Things I Used To Do":"The Things I Used To Do",
				"The Times They Are A Changin'":"The Times They Are A Changin'",
				"The Weight":"The Weight",
				"The Wheel":"The Wheel",
				"Wicked Messenger":"The Wicked Messenger",
				"They Love Each Other":"They Love Each Other",
				"This Time Forever":"This Time Forever",
				"Throwing Stones":"Throwing Stones",
				"Tiger By The Tail":"Tiger By The Tail",
				"Till The Morning Comes":"Till The Morning Comes",
				"To Lay Me Down":"To Lay Me Down",
				"Tom Dooley":"Tom Dooley",
				"Tomorrow Is A Long Time":"Tomorrow Is A Long Time",
				"Tomorrow Is Forever":"Tomorrow Is Forever",
				"Tomorrow Never Knows":"Tomorrow Never Knows",
				"Tons Of Steel":"Tons Of Steel",
				"Touch Of Gray":"Touch Of Grey",
				"*Truck Drivin' Man":"Truck Drivin' Man",
				"Truckin'":"Truckin'",
				"Turn On Your Love Light":"Turn On Your Lovelight",
				"Twist & Shout":"Twist And Shout",
				"The Stranger (Two Souls In Communion)":"Two Souls In Communion",
				"Two Trains Running":"Two Trains Running",
				"U.S. Blues":"U.S. Blues",
				"Unbroken Chain":"Unbroken Chain",
				"Uncle John's Band":"Uncle John's Band",
				"Uncle John's Band Jam":"Uncle John's Band Jam",
				"Uncle Sam Blues":"Uncle Sam Blues",
				"Valley Road":"Valley Road",
				"Victim Or The Crime":"Victim Or The Crime",
				"Viola Lee Blues":"Viola Lee Blues",
				"Visions Of Johanna":"Visions Of Johanna",
				"Wabash Cannonball":"Wabash Cannonball",
				"Wake Me Shake Me":"Wake Me Shake Me",
				"Wake Up Little Susie":"Wake Up Little Susie",
				"Walkin' Blues":"Walkin' Blues",
				"Walking The Dog":"Walking The Dog",
				"Wang Dang Doodle":"Wang Dang Doodle",
				"Warriors Of The Sun":"Warriors Of The Sun",
				"Watching The River Flow":"Watching The River Flow",
				"Wave That Flag":"Wave That Flag",
				"Wave To The Wind":"Wave To The Wind",
				"Way To Go Home":"Way To Go Home",
				"We Can Run But We Can't Hide":"We Can Run",
				"Weather Report Suite Part 1":"Weather Report Suite Part 1",
				"Weather Report Suite Prelude":"Weather Report Suite Prelude",
				"Werewolves Of London":"Werewolves Of London",
				"West L.A. Fadeaway":"West L.A. Fadeaway",
				"Wharf Rat":"Wharf Rat",
				"What's Going On?":"What's Going On?",
				"What's Become Of The Baby":"What's Become Of The Baby",
				"When I Paint My Masterpiece":"When I Paint My Masterpiece",
				"When Push Comes To Shove":"When Push Comes To Shove",
				"Where Have The Heroes Gone":"Where Have The Heroes Gone",
				"Who Do You Love?":"Who Do You Love?",
				"Who's Lovin' You Tonight":"Who's Lovin' You Tonight",
				"Why Don't We Do It In The Road":"Why Don't We Do It In The Road",
				"Hand Jive":"Willie & The Hand Jive",
				"Winin' Boy Blues":"Winin' Boy Blues",
				"Wipe Out":"Wipe Out",
				"Workin' Man Blues":"Workin' Man Blues",
				"Yellow Dog Story":"Yellow Dog Story",
				"You Ain't Woman Enough":"You Ain't Woman Enough",
				"You See A Broken Heart":"You See A Broken Heart",
				"You Win Again":"You Win Again",
				"You Won't Find Me":"You Won't Find Me",
				"Your Love At Home":"Your Love At Home"
}
